---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(shiny)
library(shinythemes)

oscars <- read_csv("data/oscars.csv")
```

```{r}
oscars <- oscars %>% 
  mutate(decades = case_when(
    (year %in% c(1927, 1928, 1929) ~ "1920s"),
    (year %in% c(1930, 1931, 1932, 1933, 1934,
                 1935, 1936, 1937, 1938, 1939) ~ "1930s"),
    (year %in% c(1940, 1941, 1942, 1943, 1944,
                 1945, 1946, 1947, 1948, 1949) ~ "1940s"),
    (year %in% c(1950, 1951, 1952, 1953, 1954,
                 1955, 1956, 1957, 1958, 1959) ~ "1950s"),
    (year %in% c(1960, 1961, 1962, 1963, 1964,
                 1965, 1966, 1967, 1968, 1969) ~ "1960s"),
    (year %in% c(1970, 1971, 1972, 1973, 1974,
                 1975, 1976, 1977, 1978, 1979) ~ "1970s"),
    (year %in% c(1980, 1981, 1982, 1983, 1984,
                 1985, 1986, 1987, 1988, 1989) ~ "1980s"),
    (year %in% c(1990, 1991, 1992, 1993, 1994,
                 1995, 1996, 1997, 1998, 1999) ~ "1990s"),
    (year %in% c(2000, 2001, 2002, 2003, 2004,
                 2005, 2006, 2007, 2008, 2009) ~ "2000s"),
    (year %in% c(2010, 2011, 2012, 2013, 2014,
                 2015, 2016, 2017) ~ "2010s"),
    
    TRUE  ~ "other")
  )
```

```{r}
best_picture_winners <- oscars %>% 
  filter (winner == TRUE) %>% 
  filter (category %in% c("BEST PICTURE", "OUTSTANDING PICTURE", 
                          "OUTSTANDING PRODUCTION", "OUTSTANDING MOTION PICTURE",
                          "BEST MOTION PICTURE", "ACTOR", "ACTRESS",
                          "ACTOR IN A LEADING ROLE", "ACTRESS IN A LEADING ROLE"))
```

```{r}
best_picture_winners <- best_picture_winners %>% 
  mutate(winning_category = case_when(
    (category %in% c("BEST PICTURE", "OUTSTANDING PICTURE", "OUTSTANDING PRODUCTION",
                     "OUTSTANDING MOTION PICTURE","BEST MOTION PICTURE")
                                                    ~ "Best Picture"),
    (category %in% c("ACTRESS", "ACTRESS IN A LEADING ROLE") ~ "Best Actress"),
    (category %in% c("ACTOR", "ACTOR IN A LEADING ROLE") ~ "Best Actor"),
    TRUE  ~ "other")
  )
```

```{r}
write_csv(best_picture_winners, "data/winners.csv")
```






